name: Create Pull Request

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-18.04
    steps:
      - name: Get issue number from branch name
        id: get-issue-number
        run: echo "::set-output name=number::$(echo ${GITHUB_REF#refs/heads/feature/})"

      - name: Get issue title
        id: get-issue-title
        run: |
          curl https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.get-issue-number.outputs.number }} \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          | jq -r '.title' \
          | echo "::set-output name=title::$(cat)"

      - name: Create Pull Request
        run: echo "#${{ steps.get-issue-number.outputs.number}} ${{ steps.get-issue-title.outputs.title }}"
