name: Create Pull Request

on:
  - push

jobs:
  create-pull-request:
    runs-on: ubuntu-18.04
    steps:
      - name: Get issue number from branch name
        id: get-issue-number
        run: echo "::set-output name=\number::${{ github.ref }}"

      - name: Get issues
        run: |
          curl https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.get-issue-number.outputs.number }} \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
